---
title: "Introduction to AiES"
author: "Shinji Tokunaga, Masafumi Funakoshim, Toshiyuki Araki"
email: s.toku@nemro.jp
package: AiES
abstract: >
 `r BiocStyle::Biocpkg("AiES")` is a free and open-source R-package for (high-throughput) axonal integrity analysis of micrographs such as murine dorsal root ganglia explant cultures. `r BiocStyle::Biocpkg("AiES")` offers tools to segment neurites, extract quantitative features, generate SVM models, and quantify axon integrity.`r BiocStyle::Biocpkg("AiES")` is available via GitHub at https://github.com/BreezyCave/AiES under the 3-Clause BSD license. 
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
graphics: yes
vignette: >
  %\VignetteIndexEntry{Introduction to AiES}
  %\VignetteKeywords{image processing, visualization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Axon Integrity Index Calculation Guide

This document explains the process of calculating the Axon Integrity Index (and Degeneration Index) from image data using three functions: axDistmap(), axSvm(), and axQnt().

## 1. Feature Extraction using axDistmap()

The axDistmap() function creates distance maps and binary images from TIFF image files, extracting relevant features.

```r
library(YourPackageName)

# You will be prompted to select a directory containing image files
axDistmap(subBack = 30, Binary = TRUE, allFeatures = TRUE, imgType = "png")
```

This function processes all TIFF files in the selected directory, generating for each image:
- A distance map image
- A binary image (optional)
- A text file containing feature data

## 2. SVM Model Creation using axSvm()

The axSvm() function creates an SVM model using the extracted features.

```r
# You will be prompted to select a directory containing data for degenerate axons
# Then, you will be prompted to select a directory containing data for intact axons
axSvm(nCst = 3, nGmm = 0.1, nCrss = 5)
```

This function generates:
- An extracted data file for machine learning
- A trained SVM model file

## 3. Axon Integrity Index Calculation using axQnt()

The axQnt() function uses the created SVM model to calculate the Axon Integrity Index and Degeneration Index for new image data.

```r
# You will first be prompted to select an SVM model file
# Then, you will be prompted to select a directory containing images or data files to process
axQnt(imprtImg = TRUE, subBack = 30, expSip = TRUE)
```

This function generates:
- A summary CSV file containing the Axon Integrity Index and Degeneration Index for each image
- (Optional) Single image prediction data files

## Summary

By executing these three functions in sequence, you can efficiently calculate the Axon Integrity Index and Degeneration Index from image data. Review the files generated at each step and adjust settings as necessary.
